[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "toggle_dpms",
  "magnify",
  "shortcuts_menu",
  "toggle_special",
  "workspaces_follow_focus",
  "wallpapers"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[shortcuts_menu.entries]
"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.2; hyprpicker --format [format] | wl-copy" # sleep to let the menu close before the picker opens
]

"Android Tools" = [
	{name="mode", options=["Mirror", "Mirror - No Control", "Record", "Record - No Window", "New Display"]},
	{name="video", options=["Display", "Camera - Back", "Camera - Front", "Webcam", "No Video"]},
	{name="audio", options=["Output", "Playback", "Mic", "Voice Call", "Voice Call Uplink", "Voice Call Downlink", "Mic Communication", "Mic Camcorder"]},
	"sleep 0.5; /home/satyam/user-scripts/android-tools.sh '[mode]' '[video]' '[audio]' > /tmp/android_tools.log"
]

[wallpapers]
unique = true
path = "/home/satyam/Personaization/Wallpapers"
interval = 3
extensions = ["jpg", "jpeg", "png"]
recurse = true
command = '/home/satyam/.config/hypr/scripts/change_wallpaper_swww.sh "[file]"'
clear_command = "swww clear"
