"$schema" = 'https://starship.rs/config-schema.json'

#format = """
#[â•­â”€$username[@$hostname](green) ](bold blue)$directory$git_branch$git_status
#[â•°â”€ ](bold blue)$character"""

right_format="$time"

command_timeout = 1000

[username]
disabled = false
show_always = true
format = "[[â•­â”€](#62B169) $user]($style)"
style_user = "bold #7CB7FF"
style_root = "bold green"

[character]
success_symbol = "[î¯†](#29DBCD)" # âœ
error_symbol = "[âœ—](bold red)"
vimcmd_symbol = "[â†](bold green)"
format = "[â•°â”€ ](#62B169)$symbol "

[hostname]
disabled = false
ssh_only = false
format = "[[@](#AFACF7)$hostname]($style)"
style = "#00FFFF"
trim_at = ""

[directory]
truncation_length = 0
truncate_to_repo = true
format = " [in]()[ $path]($style)[$read_only]($read_only_style)"
style = "bold cyan"
read_only = " ó°Œ¾" # ğŸ”’
home_symbol = "~"
truncation_symbol = "repo:"

[sudo]
style = 'bold green'
#symbol = 'ğŸ‘©â€ğŸ’»'
symbol = "î·"
disabled = false
format = ' [[as]() $symbol]($style)'

[directory.substitutions]

[git_branch]
symbol = "ï˜"
format = " [$symbol $branch(:$remote_branch)]($style)"
style = "bold purple"

[git_metrics]
format = ' ([+$added]($added_style))([-$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
format = "([âª$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashedâ¥]($style))"
style = "bold dimmed cyan"
conflicted = " âš”"
ahead = " â‡¡${count}"
behind = " â‡£${count}"
diverged = " â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = " ï“${count}"
stashed = " ó°–"
modified = " ï“’${count}"
staged = " âœš${count}"
renamed = " ï‘š${count}"
deleted = " ï“–${count}"

[git_state]
format = ' \([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"

[nodejs]
symbol = "ó°™ "
format = " [$symbol$version]($style)"
style = "bold green"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
symbol = "îœ¼ "
format = ' [$symbol$version(\($virtualenv\))]($style)'
style = "bold bright-yellow"

[bun]
disabled = true

[dart]
symbol = "î˜ "
format = ' [$symbol$version]($style)'
style = "dimmed red"

[gradle]
symbol = "îŸ² "
format = ' [$symbol$version]($style)'
style = "bold bright-cyan"

[java]
symbol = 'îœ¸ '
format = ' [$symbol$version]($style)'
style = "red dimmed"

[rust]
symbol = "î¨ "
format = " [$symbol$version-$toolchain]($style)"
style = "red dimmed"

[c]
symbol = "â„‚ "
format = " [$symbol($version(-$name))]($style)"

[cpp]
symbol = "â„‚++ "
format = " [$symbol($version(-$name))]($style)"
disabled = false

[golang]
symbol = "î˜§ "
format = " [$symbol$version]($style)"
style = "bold cyan"

[kotlin]
symbol = "î › "
format = " [$symbol($version)]($style)"
style = "bold blue"

[lua]
symbol = "î ¦ "
format = " [$symbol($version)]($style)"
style = "bold blue"

[docker_context]
symbol = "î° "
format = " [$symbol$context]($style)"
style = "bold blue"

[package]
symbol = 'ï’‡ '
format = ' [\[$symbol$version\]]($style)'
style = "208"

[time]
disabled = false
format = " [$time]($style)"
style = "italic dimmed white"
time_format = "%T"

[cmd_duration]
min_time = 3000
format = " [[took](italic dimmed white) $duration]($style)" # ó°”›
style = "italic yellow"
show_notifications = false

[memory_usage]
disabled = true
threshold = 75
symbol = "ó°› "
format = " $symbol[$ram( | $swap)]($style)"
style = "bold dimmed white"

[aws]
symbol = "î­ "
format = ' [$symbol$profile(\($region\))]($style)'
style = "bold yellow"

[kubernetes]
symbol = "ó±ƒ¾ "
format = ' [$symbol$context( \($namespace\))]($style)'
style = "bold cyan"
disabled = false
